app:
  build: .
  environment:
    INSERTION_QUEUE: insertion.queue
    VALIDATION_QUEUE: validation.queue
    NUMBER_OF_VALIDATION_CONSUMERS: 1
    RESPONSE_EXCHANGE: response.exchange
    RESPONSE_ROUTING_KEY: response.routing.key
    RABBITMQ_HOST: rabbitmq
    RABBITMQ_PORT: 5672
    RABBITMQ_VHOST: /
    RABBITMQ_USERNAME: guest
    RABBITMQ_PASSWORD: guest
    JDBC_URL: jdbc:mysql://mysql:3306/axr_challenge?user=root&password=secret
  #ports: 
  #  - "8085:8085" # expose ports 8085 - remove after testing
  #volumes:
  #    - /tmp:/tmp # volumes deve ser removido após os testes
  links:
    - mysql:mysql
    - rabbitmq:rabbitmq
  
mysql:
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: axr_challenge
    MYSQL_ROOT_PASSWORD: secret
  ports:
    - "3306:3306" # expose port 3306 - remove after testing
  
rabbitmq:
  image: rabbitmq:3.6-management
  ports:
    - 5672:5672 # expose port 5672 - remove after testing
    - 15672:15672
